spring.application.name=schoolbackend
# MongoDB Connection
spring.mongodb.uri=mongodb+srv://jitesh:jiteshPass@cluster0.tnoqq4s.mongodb.net/school_db?appName=Cluster0

# Optional: Logging for debugging
logging.level.org.springframework.data.mongodb=DEBUG